# Getting Started with cognitive3dpy

This notebook walks through the main data streams available in `cognitive3dpy`:
sessions, events, objectives, session-level objective steps, and exit polls.

## Installation

```bash
pip install cognitive3dpy
```

For pandas output support:
```bash
pip install "cognitive3dpy[pandas]"
```

## Authentication

Store your API key in a `.env` file (never commit this):

```
C3D_API_KEY=your_api_key_here
```

Then authenticate and set your project:

In [1]:
from dotenv import load_dotenv
load_dotenv()  # loads C3D_API_KEY from .env

import cognitive3dpy as c3d

c3d.c3d_auth()       # reads C3D_API_KEY from environment
c3d.c3d_project(2797)   # replace with your project ID

## Sessions

`c3d_sessions()` returns one row per session with device info, location, and Cognitive3D metric scores.

By default it returns the last 30 days and ~40 curated columns (`compact=True`).

In [2]:
sessions = c3d.c3d_sessions(n=200)
print(sessions.shape)
sessions.head()

(10, 79)

shape: (5, 79)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_i ┆ session_i ┆ session_d ┆ end_date  ┆ … ┆ c3d_metri ┆ c3d_metri ┆ c3d_sessi ┆ c3d_sess │
│ d         ┆ d         ┆ ate       ┆ ---       ┆   ┆ c_compone ┆ c_compone ┆ on_tag_ju ┆ ion_tag_ │
│ ---       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ nts_dynam ┆ nts_dynam ┆ nk        ┆ test     │
│ i64       ┆ str       ┆ datetime[ ┆ μs, UTC]  ┆   ┆ ic_…      ┆ ic_…      ┆ ---       ┆ ---      │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆ ---       ┆ ---       ┆ bool      ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2797      ┆ 177325951 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 2_5b5bf77 ┆ 1 20:05:1 ┆ 1 20:07:1 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 2.620 UTC ┆ 2.324 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 177325944 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 3_5b5bf77 ┆ 1 20:04:0 ┆ 1 20:05:0 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 3.449 UTC ┆ 1.455 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 177325933 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 6_5b5bf77 ┆ 1 20:02:1 ┆ 1 20:03:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 6.185 UTC ┆ 2.041 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 177325830 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 1_5b5bf77 ┆ 1 19:45:0 ┆ 1 19:47:0 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 1.190 UTC ┆ 6.170 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 177325581 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 9_5b5bf77 ┆ 1 19:03:3 ┆ 1 19:06:1 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 9.666 UTC ┆ 0.312 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
# Custom date range
sessions = c3d.c3d_sessions(
    start_date="2025-10-01",
    end_date="Mar 1, 2026"
)
sessions.sort(['session_date']).head()

shape: (5, 79)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_i ┆ session_i ┆ session_d ┆ end_date  ┆ … ┆ c3d_metri ┆ c3d_metri ┆ c3d_sessi ┆ c3d_sess │
│ d         ┆ d         ┆ ate       ┆ ---       ┆   ┆ c_compone ┆ c_compone ┆ on_tag_ju ┆ ion_tag_ │
│ ---       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ nts_dynam ┆ nts_dynam ┆ nk        ┆ test     │
│ i64       ┆ str       ┆ datetime[ ┆ μs, UTC]  ┆   ┆ ic_…      ┆ ic_…      ┆ ---       ┆ ---      │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆ ---       ┆ ---       ┆ bool      ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2797      ┆ 176282039 ┆ 2025-11-1 ┆ 2025-11-1 ┆ … ┆ 0.0       ┆ 1.769912  ┆ false     ┆ false    │
│           ┆ 9_2848c95 ┆ 1 00:19:5 ┆ 1 00:20:1 ┆   ┆           ┆           ┆           ┆          │
│           ┆ f3e1d596b ┆ 9.694 UTC ┆ 5.212 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dbd…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 176765122 ┆ 2026-01-0 ┆ 2026-02-1 ┆ … ┆ 0.0       ┆ 1.732467  ┆ false     ┆ false    │
│           ┆ 3_112988b ┆ 5 22:13:4 ┆ 0 22:34:3 ┆   ┆           ┆           ┆           ┆          │
│           ┆ c75b6b4f5 ┆ 3.981 UTC ┆ 3.270 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 176921302 ┆ 2026-01-2 ┆ 2026-01-2 ┆ … ┆ 0.0       ┆ 4.788802  ┆ false     ┆ false    │
│           ┆ 7_3acf6ca ┆ 4 00:03:4 ┆ 4 00:03:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆ e105d7976 ┆ 7.018 UTC ┆ 5.570 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ c04…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 176921304 ┆ 2026-01-2 ┆ 2026-01-2 ┆ … ┆ 0.0       ┆ 0.656359  ┆ false     ┆ false    │
│           ┆ 4_3acf6ca ┆ 4 00:04:0 ┆ 4 00:04:1 ┆   ┆           ┆           ┆           ┆          │
│           ┆ e105d7976 ┆ 4.700 UTC ┆ 6.195 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ c04…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 177084583 ┆ 2026-02-1 ┆ 2026-02-1 ┆ … ┆ 0.0       ┆ 0.27578   ┆ false     ┆ false    │
│           ┆ 2_112988b ┆ 1 21:37:1 ┆ 1 21:43:2 ┆   ┆           ┆           ┆           ┆          │
│           ┆ c75b6b4f5 ┆ 2.677 UTC ┆ 2.318 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
# All columns (not just compact)
sessions_full = c3d.c3d_sessions(n=100, compact=False)
print(sessions_full.columns)

['session_id', 'project_id', 'organization_id', 'participant_id', 'session_date', 'end_date', 'gaze_interval', 'hmd', 'user', 'device_id', 'user_key', 'has_gaze', 'has_fixation', 'has_event', 'has_dynamic', 'has_sensor', 'has_boundary', 'position_limited', 'gaze_limited', 'fixations_limited', 'events_limited', 'c3d_device_gpu_vendor', 'c3d_participant_oculus_id', 'c3d_participant_name', 'c3d_app_android_plugin_version', 'c3d_device_cpu', 'c3d_geo_subdivision', 'c3d_app_sdktype', 'c3d_device_gpu', 'c3d_device_os', 'c3d_app_oculus_appid', 'c3d_geo_country_iso', 'c3d_app_name', 'c3d_app_version', 'c3d_device_type', 'c3d_roomsize_description_meters', 'c3d_geo_country', 'c3d_app_xrplugin', 'c3d_version', 'c3d_participant_oculus_username', 'c3d_device_cpu_vendor', 'c3d_geo_city', 'c3d_device_hmd_type', 'c3d_deviceid', 'c3d_app_engine', 'c3d_participant_id', 'c3d_app_engine_version', 'c3d_participant_oculus_display_name', 'c3d_geo_qualified_subdivision_iso', 'c3d_geo_subdivision_iso', 'c3d_device_model', 'c3d_sessionname', 'c3d_session_sensor_c3d_battery_temp_avg', 'c3d_metric_components_controller_ergo_counts_horizontal_far', 'c3d_metric_components_comfort_score_controller_ergonomic_score_vertical_reach_score', 'c3d_metric_components_controller_ergo_counts_vertical_far', 'c3d_debug_metrics_fps_data_point_count', 'c3d_metric_components_presence_score_controller_movement_score', 'c3d_session_sensor_c3d_cpu_level_min', 'c3d_debug_metrics_fps_data_point_sum', 'c3d_metric_components_controller_ergo_counts_horizontal_medium', 'c3d_metrics_immersion_score', 'c3d_session_sensor_c3d_fps_avg_min', 'c3d_metrics_orientation_score', 'c3d_metric_components_comfort_score_head_orientation_score_pitch_score', 'c3d_metric_components_cyberwellness_acceleration_variability', 'c3d_metrics_app_performance', 'c3d_session_sensor_c3d_hmd_pitch_avg', 'c3d_session_sensor_c3d_app_meta_space_warp_min', 'c3d_session_sensor_c3d_fps_avg_max', 'c3d_metrics_ergonomics_score', 'c3d_session_sensor_c3d_fps_1pl_max', 'c3d_session_sensor_c3d_fps_5pl_min', 'c3d_session_sensor_c3d_gpu_level_max', 'c3d_metric_components_fps_score_degree_app_performance', 'c3d_metric_components_comfort_score_controller_ergonomic_score_horizontal_reach_score', 'c3d_metric_components_cyberwellness_visual_continuity', 'c3d_session_sensor_c3d_app_wifi_rssi_avg', 'c3d_session_sensor_c3d_controller_right_height_from_hmd_avg', 'c3d_session_sensor_hmd_battery_level_max', 'c3d_metric_components_presence_score_interruption_score', 'c3d_session_sensor_c3d_gpu_level_min', 'c3d_session_sensor_c3d_profiler_main_thread_time_in_ms_min', 'c3d_session_sensor_c3d_fps_5pl_max', 'c3d_session_sensor_c3d_controller_left_height_from_hmd_max', 'c3d_session_sensor_hmd_battery_level_avg', 'c3d_metric_components_cyberwellness_translational_movement', 'c3d_session_sensor_hmd_battery_status_avg', 'c3d_metric_components_comfort_score_controller_ergonomic_score', 'c3d_session_sensor_c3d_profiler_main_thread_time_in_ms_max', 'c3d_session_sensor_c3d_hmd_yaw_avg', 'c3d_metric_components_controller_ergo_counts_forwards_medium', 'c3d_metric_components_fps_data_point_sum', 'c3d_metric_components_controller_ergo_counts_forwards_far', 'c3d_session_sensor_c3d_fps_1pl_min', 'c3d_session_sensor_c3d_controller_left_height_from_hmd_min', 'c3d_metric_components_controller_ergo_counts_forwards_near', 'c3d_metric_components_cyberwellness_translational_speed', 'c3d_metric_components_average_controller_movement_meters_per_second', 'c3d_metric_components_controller_ergo_counts_forwards_total', 'c3d_metrics_boundary_score', 'c3d_session_sensor_c3d_is_power_saving_mode_min', 'c3d_session_sensor_c3d_profiler_draw_calls_count_max', 'c3d_metric_components_dynamic_input_none_percentage', 'c3d_session_sensor_c3d_profiler_system_memory_in_mb_avg', 'c3d_metric_components_fps_data_point_count', 'c3d_session_sensor_c3d_profiler_draw_calls_count_min', 'c3d_metrics_controller_engagement_score', 'c3d_metrics_comfort_score', 'c3d_metric_components_fps_score_session_percentage', 'c3d_session_sensor_c3d_is_power_saving_mode_max', 'c3d_metrics_fps_score', 'c3d_session_sensor_c3d_cpu_level_max', 'c3d_metric_components_battery_drain_sum', 'c3d_roomsize_meters', 'c3d_session_sensor_c3d_battery_temp_min', 'c3d_session_sensor_c3d_controller_right_height_from_hmd_max', 'c3d_metric_components_battery_drain_time_millis', 'c3d_session_sensor_c3d_cpu_level_avg', 'c3d_metrics_controller_events_score', 'c3d_session_sensor_c3d_hmd_pitch_max', 'c3d_metrics_presence_score', 'c3d_session_sensor_c3d_fps_avg_avg', 'c3d_metric_components_comfort_score_head_orientation_score_roll_score', 'c3d_session_sensor_c3d_hmd_pitch_min', 'c3d_session_sensor_c3d_app_meta_space_warp_avg', 'c3d_metric_components_comfort_score_controller_ergonomic_score_forward_reach_score', 'c3d_metric_components_controller_ergo_counts_horizontal_total', 'c3d_metrics_dynamic_engagement_score', 'c3d_metrics_battery_efficiency', 'c3d_geo_longitude', 'c3d_session_sensor_c3d_fps_5pl_avg', 'c3d_geo_latitude', 'c3d_metric_components_comfort_score_head_orientation_score', 'c3d_session_sensor_c3d_battery_temp_max', 'c3d_metric_components_fps_score_consistency_app_performance', 'c3d_metric_components_presence_score_gaze_exploration_score', 'c3d_session_sensor_c3d_app_wifi_rssi_min', 'c3d_session_sensor_c3d_controller_right_height_from_hmd_min', 'c3d_metric_components_dynamic_input_controller_percentage', 'c3d_session_sensor_c3d_hmd_yaw_max', 'c3d_session_sensor_c3d_gpu_level_avg', 'c3d_session_sensor_c3d_profiler_main_thread_time_in_ms_avg', 'c3d_participant_height', 'c3d_session_sensor_hmd_battery_level_min', 'c3d_debug_info_merge_timestamp_millis', 'c3d_session_sensor_hmd_battery_status_min', 'c3d_session_sensor_c3d_profiler_system_memory_in_mb_max', 'c3d_session_sensor_c3d_app_wifi_rssi_max', 'c3d_session_sensor_c3d_app_meta_space_warp_max', 'c3d_device_memory', 'c3d_session_sensor_c3d_hmd_yaw_min', 'c3d_metrics_cyberwellness_score', 'c3d_metric_components_presence_score_spatial_coverage_score', 'c3d_session_sensor_c3d_fps_1pl_avg', 'c3d_metrics_average_fps', 'c3d_session_sensor_c3d_controller_left_height_from_hmd_avg', 'c3d_session_sensor_hmd_battery_status_max', 'c3d_metrics_standing_percentage', 'c3d_session_sensor_c3d_is_power_saving_mode_avg', 'c3d_metric_components_fps_score_fluctuation_app_performance', 'c3d_metric_components_cyberwellness_continuous_movement', 'c3d_session_sensor_c3d_profiler_system_memory_in_mb_min', 'c3d_metric_components_dynamic_input_hand_percentage', 'c3d_metric_components_controller_ergo_counts_vertical_medium', 'c3d_session_sensor_c3d_profiler_draw_calls_count_avg', 'c3d_metric_components_controller_ergo_counts_vertical_near', 'c3d_metric_components_controller_ergo_counts_vertical_total', 'c3d_metric_components_controller_ergo_counts_horizontal_near', 'c3d_device_eyetracking_enabled', 'c3d_app_handtracking_enabled', 'c3d_app_in_editor', 'c3d_session_tag_junk', 'c3d_device_controllerinputs_enabled', 'c3d_session_tag_test', 'c3d_remote_variable_movement_type', 'c3d_remote_variable_number_breakable_gameobjects', 'c3d_remote_variable_coins_spawned', 'c3d_session_sensor_performance_test_frame_sensor_max', 'c3d_session_sensor_performance_test_frame_sensor_min', 'c3d_session_sensor_performance_test_frame_sensor_avg', 'c3d_session_tag_testgroupb', 'c3d_session_tag_testgroupa', 'sdk_session_id', 'created_at', 'start_time', 'tags', 'friendly_name', 'duration_s']

### Scene sessions

Use `session_type="scene"` to get one row per session-scene combination.
Useful for comparing metrics across scenes within the same session.

In [5]:
scene_sessions = c3d.c3d_sessions(session_type="scene", n=200)
scene_sessions.head()

shape: (5, 81)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_i ┆ session_i ┆ session_d ┆ end_date  ┆ … ┆ c3d_metri ┆ c3d_metri ┆ c3d_sessi ┆ c3d_sess │
│ d         ┆ d         ┆ ate       ┆ ---       ┆   ┆ c_compone ┆ c_compone ┆ on_tag_ju ┆ ion_tag_ │
│ ---       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ nts_dynam ┆ nts_dynam ┆ nk        ┆ test     │
│ i64       ┆ str       ┆ datetime[ ┆ μs, UTC]  ┆   ┆ ic_…      ┆ ic_…      ┆ ---       ┆ ---      │
│           ┆           ┆ μs, UTC]  ┆           ┆   ┆ ---       ┆ ---       ┆ bool      ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2797      ┆ 177325951 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 2_5b5bf77 ┆ 1 20:05:3 ┆ 1 20:07:1 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 3.208 UTC ┆ 2.324 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 177325944 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 3_5b5bf77 ┆ 1 20:04:1 ┆ 1 20:05:0 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 7.509 UTC ┆ 1.455 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 177325933 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 6_5b5bf77 ┆ 1 20:02:3 ┆ 1 20:03:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 0.773 UTC ┆ 2.041 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 177325830 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 1_5b5bf77 ┆ 1 19:45:2 ┆ 1 19:47:0 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 1.983 UTC ┆ 6.170 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ 177325581 ┆ 2026-03-1 ┆ 2026-03-1 ┆ … ┆ 0.0       ┆ 0.0       ┆ false     ┆ false    │
│           ┆ 9_5b5bf77 ┆ 1 19:04:0 ┆ 1 19:06:1 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 47b54905c ┆ 8.643 UTC ┆ 0.312 UTC ┆   ┆           ┆           ┆           ┆          │
│           ┆ dfc…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
# Filter to a specific scene
scene_session_filtered = c3d.c3d_sessions(
    session_type="scene",
    scene_id="bd07b0ee-41d6-438d-a01c-ba0e3d92db44", # replace this with your scene ID
    n=200,
)
scene_session_filtered.head()

/var/folders/gz/pzplpwtn35zc8sz_8zk9zqb00000gn/T/ipykernel_58687/2513579795.py:2: UserWarning: c3d_sessions() returned 0 rows. Check your date range, project ID, and filters.
  scene_session_filtered = c3d.c3d_sessions(

shape: (0, 0)
┌┐
╞╡
└┘

### Working with metric columns

All `c3d_metrics_*` and `c3d_metric_components_*` columns are `Float64`.

In [7]:
import polars as pl

# Summary stats for top-level metric scores
metric_cols = [c for c in sessions.columns if c.startswith("c3d_metrics")]
sessions.select(metric_cols).describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ c3d_metri ┆ c3d_metri ┆ c3d_metri ┆ … ┆ c3d_metri ┆ c3d_metri ┆ c3d_metri ┆ c3d_metr │
│ ---       ┆ cs_fps_sc ┆ cs_app_pe ┆ cs_averag ┆   ┆ cs_contro ┆ cs_dynami ┆ cs_standi ┆ ics_cybe │
│ str       ┆ ore       ┆ rformance ┆ e_fps     ┆   ┆ ller_enga ┆ c_engagem ┆ ng_percen ┆ rwellnes │
│           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ gem…      ┆ ent…      ┆ tag…      ┆ s_scor…  │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 8.0       ┆ 8.0       ┆ 8.0       ┆ … ┆ 8.0       ┆ 8.0       ┆ 8.0       ┆ 5.0      │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 3.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 61.66634  ┆ 45.099381 ┆ 61.737338 ┆ … ┆ 76.171563 ┆ 31.25     ┆ 0.164068  ┆ 34.24872 │
│ std       ┆ 26.551993 ┆ 10.096179 ┆ 14.196719 ┆ … ┆ 27.619617 ┆ 36.985518 ┆ 0.206709  ┆ 9.042106 │
│ min       ┆ 31.843854 ┆ 26.15834  ┆ 35.546056 ┆ … ┆ 29.573446 ┆ 0.0       ┆ 0.0       ┆ 19.50120 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 25%       ┆ 39.205231 ┆ 44.596605 ┆ 58.70491  ┆ … ┆ 80.299341 ┆ 1.0       ┆ 0.011465  ┆ 31.80507 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ 50%       ┆ 72.994679 ┆ 50.0      ┆ 70.824364 ┆ … ┆ 83.366437 ┆ 31.0      ┆ 0.128571  ┆ 38.14898 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ 75%       ┆ 84.338527 ┆ 50.0      ┆ 71.06043  ┆ … ┆ 96.353463 ┆ 53.0      ┆ 0.176471  ┆ 40.74907 │
│ max       ┆ 93.934562 ┆ 56.387486 ┆ 71.979607 ┆ … ┆ 99.994444 ┆ 100.0     ┆ 0.625     ┆ 41.03926 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
# Average FPS score by HMD
(
    sessions
    .group_by("c3d_device_model")
    .agg(pl.col("c3d_metrics_fps_score").mean().alias("avg_fps_score"))
    .sort("avg_fps_score", descending=True)
)

shape: (1, 2)
┌──────────────────┬───────────────┐
│ c3d_device_model ┆ avg_fps_score │
│ ---              ┆ ---           │
│ str              ┆ f64           │
╞══════════════════╪═══════════════╡
│ Oculus Quest     ┆ 61.66634      │
└──────────────────┴───────────────┘

### Pandas output

Pass `output="pandas"` to any function to get a pandas DataFrame instead.

In [9]:
sessions_pd = c3d.c3d_sessions(n=100, output="pandas")
sessions_pd.dtypes

project_id                                                                 int64
session_id                                                                   str
session_date                                                 datetime64[us, UTC]
end_date                                                     datetime64[us, UTC]
duration_s                                                               float64
                                                                    ...
c3d_metric_components_dynamic_input_controller_percentage                float64
c3d_metric_components_dynamic_input_hand_percentage                      float64
c3d_metric_components_dynamic_input_none_percentage                      float64
c3d_session_tag_junk                                                        bool
c3d_session_tag_test                                                        bool
Length: 79, dtype: object

## Events

`c3d_events()` returns one row per in-session event. Object IDs are resolved to friendly names and scene version IDs to scene names. Custom event properties appear as `prop_*` columns.

In [10]:
events = c3d.c3d_events(start_date="2025-01-01", n=50)
print(events.shape)
events.head()

1555 event(s) had an unrecognised object_id and will have null object name.

(1698, 34)

shape: (5, 34)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ project_id ┆ session_id ┆ participa ┆ user_key  ┆ … ┆ prop_answ ┆ duration_ ┆ object ┆ scene_nam │
│ ---        ┆ ---        ┆ nt_id     ┆ ---       ┆   ┆ er3       ┆ s         ┆ ---    ┆ e         │
│ i64        ┆ str        ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str    ┆ ---       │
│            ┆            ┆ str       ┆           ┆   ┆ i64       ┆ f64       ┆        ┆ str       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 2797       ┆ 1773259512 ┆ 564738291 ┆ 564738291 ┆ … ┆ null      ┆ 119.704   ┆ null   ┆ Level 0 - │
│            ┆ _5b5bf7747 ┆ 0564738   ┆ 0564738   ┆   ┆           ┆           ┆        ┆ Onboardin │
│            ┆ b54905cdfc ┆           ┆           ┆   ┆           ┆           ┆        ┆ g         │
│            ┆ …          ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 2797       ┆ 1773259512 ┆ 564738291 ┆ 564738291 ┆ … ┆ null      ┆ 119.704   ┆ null   ┆ Level 0 - │
│            ┆ _5b5bf7747 ┆ 0564738   ┆ 0564738   ┆   ┆           ┆           ┆        ┆ Onboardin │
│            ┆ b54905cdfc ┆           ┆           ┆   ┆           ┆           ┆        ┆ g         │
│            ┆ …          ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 2797       ┆ 1773259512 ┆ 564738291 ┆ 564738291 ┆ … ┆ null      ┆ 119.704   ┆ null   ┆ Level 0 - │
│            ┆ _5b5bf7747 ┆ 0564738   ┆ 0564738   ┆   ┆           ┆           ┆        ┆ Onboardin │
│            ┆ b54905cdfc ┆           ┆           ┆   ┆           ┆           ┆        ┆ g         │
│            ┆ …          ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 2797       ┆ 1773259512 ┆ 564738291 ┆ 564738291 ┆ … ┆ null      ┆ 119.704   ┆ null   ┆ Level 0 - │
│            ┆ _5b5bf7747 ┆ 0564738   ┆ 0564738   ┆   ┆           ┆           ┆        ┆ Onboardin │
│            ┆ b54905cdfc ┆           ┆           ┆   ┆           ┆           ┆        ┆ g         │
│            ┆ …          ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 2797       ┆ 1773259512 ┆ 564738291 ┆ 564738291 ┆ … ┆ null      ┆ 119.704   ┆ null   ┆ Level 0 - │
│            ┆ _5b5bf7747 ┆ 0564738   ┆ 0564738   ┆   ┆           ┆           ┆        ┆ Onboardin │
│            ┆ b54905cdfc ┆           ┆           ┆   ┆           ┆           ┆        ┆ g         │
│            ┆ …          ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [11]:
# Most common event types
events.group_by("event_name").len().sort("len", descending=True)

shape: (31, 2)
┌─────────────────────────────────┬─────┐
│ event_name                      ┆ len │
│ ---                             ┆ --- │
│ str                             ┆ u32 │
╞═════════════════════════════════╪═════╡
│ PerformanceTest.CustomEvent     ┆ 464 │
│ c3d.input.tracking.changed      ┆ 291 │
│ c3d.pause                       ┆ 95  │
│ c3d.Right Controller Lost trac… ┆ 91  │
│ c3d.Left Controller Lost track… ┆ 73  │
│ …                               ┆ …   │
│ c3d.exitpoll                    ┆ 5   │
│ c3d.User changed boundary       ┆ 4   │
│ Destroy All Objects             ┆ 3   │
│ c3d.User removed headset        ┆ 3   │
│ c3d.battery status changed      ┆ 1   │
└─────────────────────────────────┴─────┘

In [12]:
# Event positions — ready for spatial analysis
events.select(["event_name", "position_x", "position_y", "position_z", "object", "scene_name"])

shape: (1_698, 6)
┌─────────────────────────┬────────────┬────────────┬────────────┬────────┬────────────────────────┐
│ event_name              ┆ position_x ┆ position_y ┆ position_z ┆ object ┆ scene_name             │
│ ---                     ┆ ---        ┆ ---        ┆ ---        ┆ ---    ┆ ---                    │
│ str                     ┆ f64        ┆ f64        ┆ f64        ┆ str    ┆ str                    │
╞═════════════════════════╪════════════╪════════════╪════════════╪════════╪════════════════════════╡
│ c3d.sessionStart        ┆ 0.0        ┆ 1.48643    ┆ -0.851     ┆ null   ┆ Level 0 - Onboarding   │
│ onboarding_step_started ┆ 0.0        ┆ 1.48643    ┆ -0.851     ┆ null   ┆ Level 0 - Onboarding   │
│ onboarding_step_ended   ┆ 0.40458    ┆ 1.72507    ┆ -0.2705    ┆ null   ┆ Level 0 - Onboarding   │
│ onboarding_step_started ┆ 0.40458    ┆ 1.72507    ┆ -0.2705    ┆ null   ┆ Level 0 - Onboarding   │
│ onboarding_step_ended   ┆ -0.1924    ┆ 1.66199    ┆ -1.47013   ┆ null   ┆ Level 0 - Onboarding   │
│ …                       ┆ …          ┆ …          ┆ …          ┆ …      ┆ …                      │
│ Movement Changed        ┆ -0.62415   ┆ 0.67739    ┆ 17.430571  ┆ null   ┆ Level 1 - Fantasy      │
│                         ┆            ┆            ┆            ┆        ┆ Scene                  │
│ c3d.Right Controller    ┆ 0.00756    ┆ 0.68129    ┆ 35.936298  ┆ null   ┆ Level 1 - Fantasy      │
│ Lost trac…              ┆            ┆            ┆            ┆        ┆ Scene                  │
│ c3d.Left Controller     ┆ 0.00729    ┆ 0.68118    ┆ 35.936531  ┆ null   ┆ Level 1 - Fantasy      │
│ Lost track…             ┆            ┆            ┆            ┆        ┆ Scene                  │
│ c3d.pause               ┆ -0.00183   ┆ 0.68325    ┆ 35.941601  ┆ null   ┆ Level 1 - Fantasy      │
│                         ┆            ┆            ┆            ┆        ┆ Scene                  │
│ c3d.sessionEnd          ┆ -0.00215   ┆ 0.68323    ┆ 35.94165   ┆ null   ┆ Level 1 - Fantasy      │
│                         ┆            ┆            ┆            ┆        ┆ Scene                  │
└─────────────────────────┴────────────┴────────────┴────────────┴────────┴────────────────────────┘

## Objective Results

`c3d_objective_results()` returns aggregated success/failure counts across sessions.
Use `group_by="version"` (default) for high-level counts, or `group_by="steps"` for step-level detail.

In [13]:
# Completion rates by objective version
results = c3d.c3d_objective_results(group_by="version")
results

shape: (9, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬────────┬────────────┐
│ objective_ ┆ objective_ ┆ objective_ ┆ version_nu ┆ version_is ┆ succeeded ┆ failed ┆ completion │
│ id         ┆ name       ┆ version_id ┆ mber       ┆ _active    ┆ ---       ┆ ---    ┆ _rate      │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ i64       ┆ i64    ┆ ---        │
│ i64        ┆ str        ┆ i64        ┆ i64        ┆ bool       ┆           ┆        ┆ f64        │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪════════╪════════════╡
│ 871        ┆ Test       ┆ 1421       ┆ 2          ┆ true       ┆ 7         ┆ 3      ┆ 0.7        │
│            ┆ Object     ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ Pickup     ┆            ┆            ┆            ┆           ┆        ┆            │
│ 952        ┆ Opened     ┆ 1493       ┆ 1          ┆ true       ┆ 7         ┆ 3      ┆ 0.7        │
│            ┆ Treasure   ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ Chest      ┆            ┆            ┆            ┆           ┆        ┆            │
│ 953        ┆ Looked at  ┆ 1494       ┆ 1          ┆ true       ┆ 3         ┆ 7      ┆ 0.3        │
│            ┆ Objects    ┆            ┆            ┆            ┆           ┆        ┆            │
│ 954        ┆ Destroy    ┆ 1495       ┆ 1          ┆ true       ┆ 3         ┆ 7      ┆ 0.3        │
│            ┆ All        ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ Objects    ┆            ┆            ┆            ┆           ┆        ┆            │
│ 955        ┆ Destroy    ┆ 1496       ┆ 1          ┆ true       ┆ 2         ┆ 8      ┆ 0.2        │
│            ┆ Objects    ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ with all   ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ Weapo…     ┆            ┆            ┆            ┆           ┆        ┆            │
│ 956        ┆ Sessions   ┆ 1497       ┆ 1          ┆ true       ┆ 9         ┆ 1      ┆ 0.9        │
│            ┆ longer     ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ than 60    ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ second…    ┆            ┆            ┆            ┆           ┆        ┆            │
│ 957        ┆ Sessions   ┆ 1498       ┆ 1          ┆ true       ┆ 1         ┆ 9      ┆ 0.1        │
│            ┆ shorter    ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ than 60    ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ secon…     ┆            ┆            ┆            ┆           ┆        ┆            │
│ 958        ┆ Controller ┆ 1499       ┆ 1          ┆ true       ┆ 1         ┆ 5      ┆ 0.166667   │
│            ┆ Losing     ┆            ┆            ┆            ┆           ┆        ┆            │
│            ┆ Tracking   ┆            ┆            ┆            ┆           ┆        ┆            │
│ 959        ┆ Exited     ┆ 1500       ┆ 1          ┆ true       ┆ 1         ┆ 5      ┆ 0.166667   │
│            ┆ Boundary   ┆            ┆            ┆            ┆           ┆        ┆            │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴────────┴────────────┘

In [14]:
# Step-level breakdown
steps = c3d.c3d_objective_results(group_by="steps")
steps

shape: (16, 13)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ objective_ ┆ objective_ ┆ objective ┆ version_n ┆ … ┆ failed ┆ step_comp ┆ avg_compl ┆ avg_step_ │
│ id         ┆ name       ┆ _version_ ┆ umber     ┆   ┆ ---    ┆ letion_ra ┆ etion_tim ┆ duration_ │
│ ---        ┆ ---        ┆ id        ┆ ---       ┆   ┆ i64    ┆ te        ┆ e_s       ┆ s         │
│ i64        ┆ str        ┆ ---       ┆ i64       ┆   ┆        ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆ i64       ┆           ┆   ┆        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ 871        ┆ Test       ┆ 1421      ┆ 2         ┆ … ┆ 3      ┆ 0.7       ┆ 159.2615  ┆ 67.520286 │
│            ┆ Object     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Pickup     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 871        ┆ Test       ┆ 1421      ┆ 2         ┆ … ┆ 1      ┆ 0.9       ┆ 126.573   ┆ 36.527    │
│            ┆ Object     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Pickup     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 952        ┆ Opened     ┆ 1493      ┆ 1         ┆ … ┆ 3      ┆ 0.7       ┆ 159.2615  ┆ 159.2615  │
│            ┆ Treasure   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Chest      ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 952        ┆ Opened     ┆ 1493      ┆ 1         ┆ … ┆ 3      ┆ 0.7       ┆ 171.4303  ┆ 17.384    │
│            ┆ Treasure   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Chest      ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 953        ┆ Looked at  ┆ 1494      ┆ 1         ┆ … ┆ 7      ┆ 0.3       ┆ 244.6769  ┆ 59.391667 │
│            ┆ Objects    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …      ┆ …         ┆ …         ┆ …         │
│ 956        ┆ Sessions   ┆ 1497      ┆ 1         ┆ … ┆ 1      ┆ 0.9       ┆ 260.8287  ┆ 260.8287  │
│            ┆ longer     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ than 60    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ second…    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 957        ┆ Sessions   ┆ 1498      ┆ 1         ┆ … ┆ 9      ┆ 0.1       ┆ 260.8679  ┆ 260.8679  │
│            ┆ shorter    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ than 60    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ secon…     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 958        ┆ Controller ┆ 1499      ┆ 1         ┆ … ┆ 5      ┆ 0.166667  ┆ 92.299833 ┆ 4.607     │
│            ┆ Losing     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Tracking   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 958        ┆ Controller ┆ 1499      ┆ 1         ┆ … ┆ 5      ┆ 0.166667  ┆ 92.299833 ┆ 4.607     │
│            ┆ Losing     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Tracking   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 959        ┆ Exited     ┆ 1500      ┆ 1         ┆ … ┆ 5      ┆ 0.166667  ┆ 98.8265   ┆ 98.8265   │
│            ┆ Boundary   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

In [15]:
# Steps with low completion rates
steps.filter(pl.col("step_completion_rate") < 0.5).sort("step_completion_rate")

shape: (11, 13)
┌────────────┬────────────┬───────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ objective_ ┆ objective_ ┆ objective ┆ version_n ┆ … ┆ failed ┆ step_comp ┆ avg_compl ┆ avg_step_ │
│ id         ┆ name       ┆ _version_ ┆ umber     ┆   ┆ ---    ┆ letion_ra ┆ etion_tim ┆ duration_ │
│ ---        ┆ ---        ┆ id        ┆ ---       ┆   ┆ i64    ┆ te        ┆ e_s       ┆ s         │
│ i64        ┆ str        ┆ ---       ┆ i64       ┆   ┆        ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆ i64       ┆           ┆   ┆        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ 957        ┆ Sessions   ┆ 1498      ┆ 1         ┆ … ┆ 9      ┆ 0.1       ┆ 260.8679  ┆ 260.8679  │
│            ┆ shorter    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ than 60    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ secon…     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 958        ┆ Controller ┆ 1499      ┆ 1         ┆ … ┆ 5      ┆ 0.166667  ┆ 92.299833 ┆ 4.607     │
│            ┆ Losing     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Tracking   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 958        ┆ Controller ┆ 1499      ┆ 1         ┆ … ┆ 5      ┆ 0.166667  ┆ 92.299833 ┆ 4.607     │
│            ┆ Losing     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Tracking   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 959        ┆ Exited     ┆ 1500      ┆ 1         ┆ … ┆ 5      ┆ 0.166667  ┆ 98.8265   ┆ 98.8265   │
│            ┆ Boundary   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 953        ┆ Looked at  ┆ 1494      ┆ 1         ┆ … ┆ 7      ┆ 0.3       ┆ 244.6769  ┆ 59.391667 │
│            ┆ Objects    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …      ┆ …         ┆ …         ┆ …         │
│ 954        ┆ Destroy    ┆ 1495      ┆ 1         ┆ … ┆ 7      ┆ 0.3       ┆ 248.0777  ┆ 248.0777  │
│            ┆ All        ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Objects    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 955        ┆ Destroy    ┆ 1496      ┆ 1         ┆ … ┆ 7      ┆ 0.3       ┆ 234.7188  ┆ 34.753333 │
│            ┆ Objects    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ with all   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Weapo…     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 955        ┆ Destroy    ┆ 1496      ┆ 1         ┆ … ┆ 7      ┆ 0.3       ┆ 242.8588  ┆ 53.331333 │
│            ┆ Objects    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ with all   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Weapo…     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 953        ┆ Looked at  ┆ 1494      ┆ 1         ┆ … ┆ 6      ┆ 0.4       ┆ 239.29    ┆ 68.738    │
│            ┆ Objects    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│ 955        ┆ Destroy    ┆ 1496      ┆ 1         ┆ … ┆ 6      ┆ 0.4       ┆ 225.7562  ┆ 34.9035   │
│            ┆ Objects    ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ with all   ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
│            ┆ Weapo…     ┆           ┆           ┆   ┆        ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

## Session Objectives

`c3d_session_objectives()` returns one row per objective step per session — useful for individual-level analysis.

In [16]:
session_steps = c3d.c3d_session_objectives(start_date="2025-01-01")
session_steps.head()

shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_i ┆ scene_id  ┆ scene_nam ┆ scene_ver ┆ … ┆ step_time ┆ step_dura ┆ step_dura ┆ step_res │
│ d         ┆ ---       ┆ e         ┆ sion_id   ┆   ┆ stamp     ┆ tion      ┆ tion_sec  ┆ ult      │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆           ┆ str       ┆ i64       ┆   ┆ datetime[ ┆ i64       ┆ f64       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs, UTC]  ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2797      ┆ de704574- ┆ Level 0 - ┆ 10689     ┆ … ┆ 2026-03-1 ┆ 28852     ┆ 28.852    ┆ succeede │
│           ┆ b03f-424e ┆ Onboardin ┆           ┆   ┆ 1 20:05:4 ┆           ┆           ┆ d        │
│           ┆ -be87-498 ┆ g         ┆           ┆   ┆ 1.472 UTC ┆           ┆           ┆          │
│           ┆ 5f8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ de704574- ┆ Level 0 - ┆ 10689     ┆ … ┆ 2026-03-1 ┆ 39324     ┆ 39.324    ┆ succeede │
│           ┆ b03f-424e ┆ Onboardin ┆           ┆   ┆ 1 20:05:5 ┆           ┆           ┆ d        │
│           ┆ -be87-498 ┆ g         ┆           ┆   ┆ 1.944 UTC ┆           ┆           ┆          │
│           ┆ 5f8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ de704574- ┆ Level 0 - ┆ 10689     ┆ … ┆ 2026-03-1 ┆ 65005     ┆ 65.005    ┆ succeede │
│           ┆ b03f-424e ┆ Onboardin ┆           ┆   ┆ 1 20:06:1 ┆           ┆           ┆ d        │
│           ┆ -be87-498 ┆ g         ┆           ┆   ┆ 7.625 UTC ┆           ┆           ┆          │
│           ┆ 5f8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ de704574- ┆ Level 0 - ┆ 10689     ┆ … ┆ 2026-03-1 ┆ 119704    ┆ 119.704   ┆ failed   │
│           ┆ b03f-424e ┆ Onboardin ┆           ┆   ┆ 1 20:07:1 ┆           ┆           ┆          │
│           ┆ -be87-498 ┆ g         ┆           ┆   ┆ 2.324 UTC ┆           ┆           ┆          │
│           ┆ 5f8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2797      ┆ de704574- ┆ Level 0 - ┆ 10689     ┆ … ┆ 2026-03-1 ┆ 65005     ┆ 65.005    ┆ succeede │
│           ┆ b03f-424e ┆ Onboardin ┆           ┆   ┆ 1 20:06:1 ┆           ┆           ┆ d        │
│           ┆ -be87-498 ┆ g         ┆           ┆   ┆ 7.625 UTC ┆           ┆           ┆          │
│           ┆ 5f8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
# Average step duration per step
(
    session_steps
    .group_by(["objective_name", "step_number", "step_description"])
    .agg(pl.col("step_duration_sec").mean().alias("avg_duration_sec"))
    .sort(["objective_name", "step_number"])
)

shape: (16, 4)
┌────────────────────────────┬─────────────┬─────────────────────────────────┬──────────────────┐
│ objective_name             ┆ step_number ┆ step_description                ┆ avg_duration_sec │
│ ---                        ┆ ---         ┆ ---                             ┆ ---              │
│ str                        ┆ i64         ┆ str                             ┆ f64              │
╞════════════════════════════╪═════════════╪═════════════════════════════════╪══════════════════╡
│ Controller Losing Tracking ┆ 1           ┆ Event c3d.Left Controller Lost… ┆ 4.607            │
│ Controller Losing Tracking ┆ 2           ┆ Event c3d.Right Controller Los… ┆ 4.607            │
│ Destroy All Objects        ┆ 1           ┆ Event Destroy All Objects occu… ┆ 124.730375       │
│ Destroy Objects with all   ┆ 1           ┆ Event Destroy Object occurs at… ┆ 34.9035          │
│ Weapo…                     ┆             ┆                                 ┆                  │
│ Destroy Objects with all   ┆ 2           ┆ Event Destroy Object occurs at… ┆ 34.753333        │
│ Weapo…                     ┆             ┆                                 ┆                  │
│ …                          ┆ …           ┆ …                               ┆ …                │
│ Opened Treasure Chest      ┆ 2           ┆ Event Unlock Chest occurs at l… ┆ 16.492091        │
│ Sessions longer than 60    ┆ 1           ┆ Event c3d.sessionEnd occurs at… ┆ 140.669125       │
│ second…                    ┆             ┆                                 ┆                  │
│ Sessions shorter than 60   ┆ 1           ┆ Event c3d.sessionEnd occurs at… ┆ 140.718125       │
│ secon…                     ┆             ┆                                 ┆                  │
│ Test Object Pickup         ┆ 1           ┆ Event Pick Up Key occurs at le… ┆ 74.041           │
│ Test Object Pickup         ┆ 2           ┆ Event Pick Up Sword occurs at … ┆ 36.746824        │
└────────────────────────────┴─────────────┴─────────────────────────────────┴──────────────────┘

## Exit Polls

`c3d_exitpoll()` returns response counts per answer option, per question, per hook version.

In [18]:
polls = c3d.c3d_exitpoll()
polls

shape: (109, 8)
┌──────────────┬─────────┬──────────────┬──────────────┬─────────────┬───────┬─────────────┬───────┐
│ hook         ┆ version ┆ question_ind ┆ question_tit ┆ question_ty ┆ value ┆ value_label ┆ count │
│ ---          ┆ ---     ┆ ex           ┆ le           ┆ pe          ┆ ---   ┆ ---         ┆ ---   │
│ str          ┆ i64     ┆ ---          ┆ ---          ┆ ---         ┆ str   ┆ str         ┆ i64   │
│              ┆         ┆ i64          ┆ str          ┆ str         ┆       ┆             ┆       │
╞══════════════╪═════════╪══════════════╪══════════════╪═════════════╪═══════╪═════════════╪═══════╡
│ end_question ┆ 2       ┆ 1            ┆ Were you     ┆ boolean     ┆ 0     ┆ False       ┆ 18    │
│ s            ┆         ┆              ┆ standing     ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ during this  ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ …            ┆             ┆       ┆             ┆       │
│ end_question ┆ 2       ┆ 1            ┆ Were you     ┆ boolean     ┆ 1     ┆ True        ┆ 13    │
│ s            ┆         ┆              ┆ standing     ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ during this  ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ …            ┆             ┆       ┆             ┆       │
│ end_question ┆ 2       ┆ 2            ┆ How          ┆ scale       ┆ 10    ┆ 10          ┆ 13    │
│ s            ┆         ┆              ┆ comfortable  ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ were you     ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ durin…       ┆             ┆       ┆             ┆       │
│ end_question ┆ 2       ┆ 2            ┆ How          ┆ scale       ┆ 9     ┆ 9           ┆ 6     │
│ s            ┆         ┆              ┆ comfortable  ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ were you     ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ durin…       ┆             ┆       ┆             ┆       │
│ end_question ┆ 2       ┆ 2            ┆ How          ┆ scale       ┆ 6     ┆ 6           ┆ 5     │
│ s            ┆         ┆              ┆ comfortable  ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ were you     ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ durin…       ┆             ┆       ┆             ┆       │
│ …            ┆ …       ┆ …            ┆ …            ┆ …           ┆ …     ┆ …           ┆ …     │
│ end_question ┆ 1       ┆ 3            ┆ How immersed ┆ scale       ┆ 5     ┆ 5           ┆ 1     │
│ s_short      ┆         ┆              ┆ did you feel ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ duri…        ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 3            ┆ How immersed ┆ scale       ┆ 7     ┆ 7           ┆ 1     │
│ s_short      ┆         ┆              ┆ did you feel ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ duri…        ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 4            ┆ What was     ┆ multiple    ┆ 0     ┆ Sword       ┆ 2     │
│ s_short      ┆         ┆              ┆ your         ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ favourite    ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ weapon       ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 4            ┆ What was     ┆ multiple    ┆ 1     ┆ Torch       ┆ 2     │
│ s_short      ┆         ┆              ┆ your         ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ favourite    ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ weapon       ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 4            ┆ What was     ┆ multiple    ┆ 2     ┆ Bow         ┆ 2     │
│ s_short      ┆         ┆              ┆ your         ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ favourite    ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ weapon       ┆             ┆       ┆             ┆       │
└──────────────┴─────────┴──────────────┴──────────────┴─────────────┴───────┴─────────────┴───────┘

In [19]:
# Filter to a specific hook
polls = c3d.c3d_exitpoll(hook="end_questions_short", version=1)
polls

shape: (11, 8)
┌──────────────┬─────────┬──────────────┬──────────────┬─────────────┬───────┬─────────────┬───────┐
│ hook         ┆ version ┆ question_ind ┆ question_tit ┆ question_ty ┆ value ┆ value_label ┆ count │
│ ---          ┆ ---     ┆ ex           ┆ le           ┆ pe          ┆ ---   ┆ ---         ┆ ---   │
│ str          ┆ i64     ┆ ---          ┆ ---          ┆ ---         ┆ str   ┆ str         ┆ i64   │
│              ┆         ┆ i64          ┆ str          ┆ str         ┆       ┆             ┆       │
╞══════════════╪═════════╪══════════════╪══════════════╪═════════════╪═══════╪═════════════╪═══════╡
│ end_question ┆ 1       ┆ 1            ┆ You were     ┆ boolean     ┆ 1     ┆ True        ┆ 6     │
│ s_short      ┆         ┆              ┆ standing     ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ during this  ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ …            ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 2            ┆ How          ┆ scale       ┆ 8     ┆ 8           ┆ 3     │
│ s_short      ┆         ┆              ┆ comfortable  ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ were you     ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ durin…       ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 2            ┆ How          ┆ scale       ┆ 9     ┆ 9           ┆ 2     │
│ s_short      ┆         ┆              ┆ comfortable  ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ were you     ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ durin…       ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 2            ┆ How          ┆ scale       ┆ 7     ┆ 7           ┆ 1     │
│ s_short      ┆         ┆              ┆ comfortable  ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ were you     ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ durin…       ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 3            ┆ How immersed ┆ scale       ┆ 8     ┆ 8           ┆ 2     │
│ s_short      ┆         ┆              ┆ did you feel ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ duri…        ┆             ┆       ┆             ┆       │
│ …            ┆ …       ┆ …            ┆ …            ┆ …           ┆ …     ┆ …           ┆ …     │
│ end_question ┆ 1       ┆ 3            ┆ How immersed ┆ scale       ┆ 5     ┆ 5           ┆ 1     │
│ s_short      ┆         ┆              ┆ did you feel ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ duri…        ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 3            ┆ How immersed ┆ scale       ┆ 7     ┆ 7           ┆ 1     │
│ s_short      ┆         ┆              ┆ did you feel ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ duri…        ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 4            ┆ What was     ┆ multiple    ┆ 0     ┆ Sword       ┆ 2     │
│ s_short      ┆         ┆              ┆ your         ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ favourite    ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ weapon       ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 4            ┆ What was     ┆ multiple    ┆ 1     ┆ Torch       ┆ 2     │
│ s_short      ┆         ┆              ┆ your         ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ favourite    ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ weapon       ┆             ┆       ┆             ┆       │
│ end_question ┆ 1       ┆ 4            ┆ What was     ┆ multiple    ┆ 2     ┆ Bow         ┆ 2     │
│ s_short      ┆         ┆              ┆ your         ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ favourite    ┆             ┆       ┆             ┆       │
│              ┆         ┆              ┆ weapon       ┆             ┆       ┆             ┆       │
└──────────────┴─────────┴──────────────┴──────────────┴─────────────┴───────┴─────────────┴───────┘

In [20]:
# Response distribution for each question
(
    polls
    .with_columns(
        (pl.col("count") / pl.col("count").sum().over("question_title")).alias("pct")
    )
    .select(["question_title", "value_label", "count", "pct"])
    .sort(["question_title", "pct"], descending=[False, True])
)

shape: (11, 4)
┌─────────────────────────────────┬─────────────┬───────┬──────────┐
│ question_title                  ┆ value_label ┆ count ┆ pct      │
│ ---                             ┆ ---         ┆ ---   ┆ ---      │
│ str                             ┆ str         ┆ i64   ┆ f64      │
╞═════════════════════════════════╪═════════════╪═══════╪══════════╡
│ How comfortable were you durin… ┆ 8           ┆ 3     ┆ 0.5      │
│ How comfortable were you durin… ┆ 9           ┆ 2     ┆ 0.333333 │
│ How comfortable were you durin… ┆ 7           ┆ 1     ┆ 0.166667 │
│ How immersed did you feel duri… ┆ 8           ┆ 2     ┆ 0.333333 │
│ How immersed did you feel duri… ┆ 9           ┆ 2     ┆ 0.333333 │
│ …                               ┆ …           ┆ …     ┆ …        │
│ How immersed did you feel duri… ┆ 7           ┆ 1     ┆ 0.166667 │
│ What was your favourite weapon  ┆ Sword       ┆ 2     ┆ 0.333333 │
│ What was your favourite weapon  ┆ Torch       ┆ 2     ┆ 0.333333 │
│ What was your favourite weapon  ┆ Bow         ┆ 2     ┆ 0.333333 │
│ You were standing during this … ┆ True        ┆ 6     ┆ 1.0      │
└─────────────────────────────────┴─────────────┴───────┴──────────┘